2020-01-09 16:49:23,055 - __main__ - INFO - start print log
2020-01-09 16:49:23,064 - __main__ - WARNING - somethindg maybe fail
2020-01-09 16:49:23,065 - __main__ - INFO - finish
2020-01-09 16:53:05,552 - __main__ - INFO - start print log
2020-01-09 16:53:05,552 - __main__ - WARNING - something maybe fail
2020-01-09 16:53:05,552 - __main__ - INFO - Finish
2020-01-09 17:08:47,635 - __main__ - INFO - Start print log
2020-01-09 17:08:47,635 - __main__ - WARNING - somethindg maybe fail
2020-01-09 17:08:47,635 - __main__ - INFO - finish
2020-01-09 17:09:34,452 - __main__ - INFO - start print log
2020-01-09 17:09:34,452 - __main__ - WARNING - something maybe fail
2020-01-09 17:09:34,452 - __main__ - INFO - Finish
2020-01-09 17:10:20,493 - __main__ - INFO - start print log
2020-01-09 17:10:20,493 - __main__ - WARNING - something maybe fail
2020-01-09 17:10:20,493 - __main__ - INFO - Finish
2020-01-09 17:23:51,424 - __main__ - INFO - start print log
2020-01-09 17:23:51,424 - __main__ - WARNING - something maybe fail
2020-01-09 17:23:51,424 - __main__ - ERROR - failed to open skiearn.txt from logger.error
Traceback (most recent call last):
  File "D:/PycharmProjects/sinosun/requests_exercise/Python接口自动化/logger/log5.py", line 26, in <module>
    open("sklearn.txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'sklearn.txt'
2020-01-09 17:23:51,446 - __main__ - INFO - finish
2020-01-10 16:54:06,910 - __main__ - INFO - start print log
2020-01-10 16:54:06,928 - __main__ - WARNING - something maybe fail
2020-01-10 16:54:06,928 - __main__ - INFO - finish
